change binary to aircast instead of airupnp

diff --git a/scripts/start-stop-status b/scripts/start-stop-status
--- a/scripts/start-stop-status
+++ b/scripts/start-stop-status
@@ -4,15 +4,14 @@ set -eu
 
 AIRCONNECT_DIR="/var/packages/AirConnect/target"
 
-logfile=/tmp/airupnp.log
+logfile=/tmp/aircast.log
 
-start_airupnp ()
+start_aircast ()
 {
     ip="$1"
-    port=49154
-    echo "[$(date +'%T')] Starting airupnp on ${ip}:${port}" >> ${logfile}
+    echo "[$(date +'%T')] Starting aircast on ${ip}" >> ${logfile}
 
-    su airconnect -s /bin/sh -c "${AIRCONNECT_DIR}/airupnp -b ${ip}:${port} -z -l 1000:2000 -f ${logfile} -d all=error -d main=info" >> ${logfile} 2>&1
+    su airconnect -s /bin/sh -c "${AIRCONNECT_DIR}/aircast -b ${ip} -z -f ${logfile} -d all=error -d main=info" >> ${logfile} 2>&1
 
     cnt=0
     while [ $cnt -lt 3 ]; do
@@ -31,10 +30,10 @@ start_airconnect ()
     touch "${logfile}"
     chown airconnect:users "${logfile}"
 
-    # If you want to start the airupnp process on a specific IP please uncomment the following lines
+    # If you want to start the aircast process on a specific IP please uncomment the following lines
     # and set your own local IP address:
     #
-    # start_airupnp "1.2.3.4" || true
+    # start_aircast "1.2.3.4" || true
     # return  0
 
     interfaces=$(ifconfig -a | grep 'Ethernet' -A 1 | grep -E 'inet (addr:)?(192\.168\.|10\.)' -B 1 | grep 'Ethernet' | grep -v "lbr0" | cut -d ' ' -f 1)
@@ -50,21 +49,21 @@ start_airconnect ()
     for interface in $interfaces; do
         ip=$(/sbin/ifconfig "$interface" | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}')
         if [ -n "$ip" ]; then
-            if start_airupnp "$ip"; then
+            if start_aircast "$ip"; then
                 return 0
             else
-                killall -15 airupnp
+                killall -15 aircast
             fi
         fi
     done
 
-    echo "Failed to start airupnp on any of the local interfaces, please make sure you have at least one UPnP/Sonos device on your network" > "${SYNOPKG_TEMP_LOGFILE}"
+    echo "Failed to start aircast on any of the local interfaces, please make sure you have at least one UPnP/Sonos device on your network" > "${SYNOPKG_TEMP_LOGFILE}"
     exit 1
 }
 
 stop_airconnect ()
 {
-    killall -15 airupnp
+    killall -15 aircast
 }
 
 airconnect_status ()
@@ -72,12 +71,12 @@ airconnect_status ()
     # Check if ps has ax options
     if ps ax >/dev/null 2>&1; then
         # shellcheck disable=SC2009
-        if ! ps ax | grep airupnp | grep -v -q grep; then
+        if ! ps ax | grep aircast | grep -v -q grep; then
             return 1
         fi
     else
         # shellcheck disable=SC2009
-        if ! ps | grep airupnp | grep -v -q grep; then
+        if ! ps | grep aircast | grep -v -q grep; then
             return 1
         fi
     fi
@@ -107,7 +106,7 @@ case $1 in
         fi
         ;;
     log)
-        echo "/tmp/airupnp.log"
+        echo "/tmp/aircast.log"
         exit 0
         ;;
     *)
